name: Deploy Node.js to EC2 (SSM)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy via AWS SSM
        run: |
          aws ssm send-command \
            --instance-ids "i-09cbfd7c90bc575e2" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy Node.js backend" \
            --parameters commands='[
              "cd /home/ubuntu/finago-hotel-api-v2",
              "echo \"Current directory: $(pwd)\"",
              "rm tsconfig.build.tsbuildinfo",
              "git pull origin main",
              "npm install",
              "npm run build",
              "npm run migration:run",
              "pm2 restart finago-hotel-api-v2 || pm2 start dist/main.js --name finago-hotel-api-v2"
            ]'
