name: Deploy Node.js to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/finago-hotel-api-v2
            git pull origin main
            npm install
            npm run build
            npm run migration:run
            pm2 restart finago-hotel-api-v2 || pm2 start dist/main.js --name finago-hotel-api-v2
